name: Deploy to preview-site

on:
  push:
    branches:
      # デプロイ対象のブランチを指定
      # 複数指定すると、どのブランチでも実行してしまうので注意すること
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: 'auth'
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.FIREBASE_ADMINSDK_JSON }}'
      - uses: google-github-actions/setup-gcloud@v0
      - uses: docker/setup-buildx-action@v1
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
        if: ${{ env.RUN_BUILD == 1 }}
      - run: |
          yarn
          yarn revbuild
        if: ${{ env.RUN_BUILD == 1 }}
        env:
          RUN_BUILD: ${{ secrets.RUN_BUILD || '' }}
      - run: cp -pR ${{ secrets.PREVIEW_SOURCE }} previewer/site
      - name: Enable services of GCP
        run: gcloud services enable --project ${{ secrets.FIREBASE_PROJECT_ID }} run.googleapis.com
      - uses: docker/login-action@v1
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.FIREBASE_ADMINSDK_JSON }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: gcr.io/${{ secrets.FIREBASE_PROJECT_ID }}/previewer:build-${{ env.GITHUB_RUN_ID }}
          context: previewer
      - name: Deploy container
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          service: previewer
          image: gcr.io/${{ secrets.FIREBASE_PROJECT_ID }}/previewer:build-${{ env.GITHUB_RUN_ID }}
          region: asia-northeast1
          flags: --allow-unauthenticated
      - name: Deploy hosting
        uses: w9jds/firebase-action@master
        with:
          args: deploy
        env:
          GCP_SA_KEY: ${{ secrets.FIREBASE_ADMINSDK_JSON }}
          PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          PROJECT_PATH: ./previewer
